[package]
name = "oscen-macros"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full"] }
proc-macro2 = "1.0"

[dev-dependencies]
oscen = { path = "../oscen-lib" }
arrayvec = "0.7"
